### ISSUE TITLE
Crash During Server Startup

### ISSUE THREAD

**Issue by ghost** [Minenash/Embedded-Assets#1]
`Fabric | MC 1.19.2`

Mods List:
```
anvilrestoration-fabric_1.19.2-1.7.jar         embedded_assets-1.1.0+1.19-fabric.jar            image2map-0.3.0.jar                           RoughlyEnoughItems-9.1.555.jar
 architectury-6.3.49-fabric.jar                 enchantment-lore-1.2.9+MC1.19.1.jar              infinitetrading-fabric_1.19.2-3.1.jar         servercore-1.3.2-1.19.2.jar
 AxesAreWeapons-1.6.0-fabric-1.17.1.jar         expanded-armor-enchanting-1.0.3.jar              infinityfix-1.0.0.jar                         servertick-mc1.19-1.7.jar
 badpackets-fabric-0.2.0.jar                    expanded-axe-enchanting-1.0.4.jar                Infinity-Water-Bucket-Fabric-1.19-2.0.0.jar   servshred-1.0.8.jar
 betterbeaconplacement-fabric_1.19.2-2.1.jar    expanded-trident-enchanting-1.0.4.jar            inventorytotem-fabric_1.19.2-2.1.jar          slumber-1.0.0.jar
 betterconduitplacement-fabric_1.19.2-2.0.jar   expanded-weapon-enchanting-1.0.3.jar             journeymap-1.19.1-5.9.0beta2-fabric.jar       smoothboot-fabric-1.19-1.7.1.jar
 bettersleeping-0.6.1+1.19.jar                  extendedbonemeal-fabric_1.19.2-2.1.jar           jsst-1.19-0.1.4.jar                           sodium-fabric-mc1.19.2-0.4.4+build.18.jar
 betterspawnercontrol-fabric_1.19.2-3.1.jar     fabric-api-0.64.0+1.19.2.jar                     krypton-0.2.1.jar                             starbidous-portal-linking-fabric-1.0.0+1.19.2.jar
 BetterThanMending-1.7.2.jar                    fabric-carpet-1.19.2-1.4.84+v221018.jar          lazydfu-0.1.3.jar                             styled-chat-2.0.1+1.19.2.jar
 c2me-fabric-mc1.19.2-0.2.0+alpha.9.0.jar       fabriccrossdimtpfix-0.3.1.jar                    leaves-us-in-peace-1.0.10+MC1.19-1.19.2.jar   tectonic-mod-mc1.19-v1.0.2.jar
 Chunky-1.3.38.jar                              fabric-language-kotlin-1.8.5+kotlin.1.7.20.jar   lithium-fabric-mc1.19.2-0.10.0.jar            Terra-fabric-6.2.0-BETA+7d056bd88.jar
 cloth-config-8.2.88-fabric.jar                 fastback-0.7.3+1.19.2.jar                        megane-8.3.0.jar                              thorium-1.3.2.jar
 collective-fabric-1.19.2-5.11.jar              fastgrowth-1.7.jar                               memoryleakfix-1.19.1-0.7.0.jar                totw_additions-1.2.3-1.19.x-fabric.jar
 colorfulanvils-1.0.2+1.19.1.jar                Fastload-1.2.1.jar                               milkallthemobs-fabric_1.19.2-2.2.jar          Towns-and-Towers-1.19-1.8.2.jar
 crops_love_rain-1.3.0.jar                      ferritecore-5.0.0-fabric.jar                     mixintrace-1.1.1+1.17.jar                     treeharvester-fabric_1.19.2-5.8.jar
 Debugify-2.7.1.jar                             FoxGlow-1.5.0+fabric1.19.2.jar                   nethermap-2.0.2-1.19.2.jar                   '[Universal]CTOV-v3-1-2.jar'
 deepslatecutting-fabric-1.5.0.jar              global_packs-fabric-1.19.2-1.14.1_fabric.jar     no-enchant-cap-2.1.3+1.19.x.jar              '[Universal]Immersive_Structures_v2-0-3.jar'
 dragondropselytra-fabric_1.19.2-2.0.jar        graves-2.1.2+1.19.2.jar                          nopryingeyes-1.19.2-v1.4.0.jar                viewdistancefix-1.19.2-1.0.0.jar
 DungeonsArise-1.19-2.1.51-fabric-beta-hf.jar   grind-enchantments-1.6.4+1.19.jar                notenoughcrashes-4.1.8+1.19.2-fabric.jar      whereisit-1.19-1.14.11.jar
 Dynmap-3.4-fabric-1.19.1.jar                   healingcampfire-fabric_1.19.2-4.0.jar            phosphor-fabric-mc1.19.x-0.8.1.jar            wither-cage-fix-1.0.15+MC1.19-1.19.2.jar
 easyelytratakeoff-fabric_1.19.2-3.2.jar        hoetweaks-fabric_1.19.2-2.0.jar                  pingspam-1.3.1+1.19.2.jar                     wraith-silkspawners-1.1.2.jar
 EditSign-1.19.2-2.6.0.jar                      HorseBuff-1.19-2.0.1.jar                         repurposed_structures_fabric-6.1.2+1.19.jar   wthit-fabric-5.13.3.jar
```

Stack Trace:
```
[05:11:42] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NoClassDefFoundError: org/apache/commons/codec/digest/DigestUtils
        at Not Enough Crashes deobfuscated stack trace.(1.19.2+build.28) ~[?:?]
        at com.minenash.embedded_assets.server.LocalResourcePackHoster.calcSHA1(LocalResourcePackHoster.java:100) ~[embedded_assets-1.1.0+1.19-fabric.jar:?]
        at com.minenash.embedded_assets.server.PackCreator.create(PackCreator.java:77) ~[embedded_assets-1.1.0+1.19-fabric.jar:?]
        at com.minenash.embedded_assets.server.EmbeddedAssetsServer.generateMasterPack(EmbeddedAssetsServer.java:28) ~[embedded_assets-1.1.0+1.19-fabric.jar:?]
        at net.fabricmc.fabric.api.event.lifecycle.v1.ServerLifecycleEvents.lambda$static$2(ServerLifecycleEvents.java:49) ~[fabric-lifecycle-events-v1-2.2.0+33ffe9ec90-fbd9228dd8adfc4d.jar:?]
        at net.minecraft.server.MinecraftServer.handler$bhg000$afterSetupServer(MinecraftServer:5801) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:644) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:257) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.ClassNotFoundException: org.apache.commons.codec.digest.DigestUtils
        at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.14.10.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.10.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        ... 8 more
```

**Comment by Minenash** [comment]
Interesting. I wonder why you don't have that class.

I can replace it with a hash method that doesn't require apache commons.

Could you provide any information regarding your java?

**Comment by Minenash** [comment]
Ah, found the reason for the class not being found. The class isn't on the server, only client. But when I tested the server, I did it in the dev environment, so the class was available to the server anyways
